Redtag90/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace redtag90.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Enter your email")]
        [EmailAddress(ErrorMessage = "Enter a valid email address")]
        public string loginEmail {get;set;}

        [Required(ErrorMessage = "Enter your password")]
        [MinLength(8, ErrorMessage = "Must be at least 8 characters")]
        public string loginPassword {get;set;}
    }
}

Redtag90/Controllers/LoginRegController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using redtag90.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace redtag90.Controllers
{
    public class LoginRegController : Controller
    {
        private MyContext dbContext;
        public LoginRegController(MyContext context)
        {
            dbContext = context;
        }
//////////////////////////////////////////////////////////////////////////////////
        [HttpGet]
        [Route("register")]
        public IActionResult Register()
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                ViewBag.Login = "Login";
                ViewBag.Register = "Register";
            }
            else
            {
                ViewBag.Cart = "Cart";
                ViewBag.NewProduct = "New Product";
                ViewBag.Logout = "Logout";
            }
            return View();
        }
//////////////////////////////////////////////////////////////////////////////////        
        [HttpGet]
        [Route("login")]
        public IActionResult Login()
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                ViewBag.Login = "Login";
                ViewBag.Register = "Register";
            }
            else
            {
                ViewBag.Cart = "Cart";
                ViewBag.NewProduct = "New Product";
                ViewBag.Logout = "Logout";
            }
            return View();
        }
//////////////////////////////////////////////////////////////////////////////////
        [HttpPost("loggingin")]
        public IActionResult Login(Login login)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            User ValidateEmail = dbContext.Users.SingleOrDefault(user => user.email == login.loginEmail);
            if (ValidateEmail != null)
            {
                var Hasher = new PasswordHasher<User>();
                if(0 != Hasher.VerifyHashedPassword(ValidateEmail, ValidateEmail.password, login.loginPassword))
                {
                   HttpContext.Session.SetInt32("UserId", ValidateEmail.UserId);

                   return RedirectToAction("Index", "Home"); 
                }
                else
                {
                    ViewBag.Error = "Incorrect password or email";

                    return View();
                }
            }
            else
            {
                ViewBag.Error = "Incorrect password or email";

                return View();
            }
        }
//////////////////////////////////////////////////////////////////////////////////
        [HttpPost("Register")]
        public IActionResult Register(User newUser)
        {
            if (ModelState.IsValid)
            {
                if (dbContext.Users.Any(u => u.email == newUser.email))
                {
                    ModelState.AddModelError("Email", "Email is already in use!");
                    return View ();
                }
                PasswordHasher<User> hasher = new PasswordHasher<User>();
                newUser.password = hasher.HashPassword(newUser, newUser.password);

                dbContext.Add(newUser);
                dbContext.SaveChanges();

                HttpContext.Session.SetInt32("UserId", newUser.UserId);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////        
        [HttpGet]
        [Route("logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
/////////////////////////////////////////////////////////////////////////////////////////////////////////    
}

Redtag90/Views/LoginReg/Login.cshtml
@model Login

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="~/css/login.css"/>
    <title>RedTag90</title>
</head>
<body>    
    <h1 class="login_welcome">Welcome Back</h1>
    <div class="login">
        <form asp-controller="LoginReg" asp-action="Login" method="post">
            <p>Email: </p>
            <input class="login_input" type="email" asp-for="loginEmail">
            <br>
            <span asp-validation-for="loginEmail" style="color: red;">@ViewBag.Error</span>
            <br>
            <p>Password: </p>
            <input class="login_input" type="password" asp-for="loginPassword">
            <br>
            <span asp-validation-for="loginPassword" style="color: red;">@ViewBag.Error</span>
            <br>
            <input type="submit" value="Login">
        </form>
        <br>
        <p>Don't have an account? <a href="register">Register here</a></p>
    </div>
</body>
</html>

Redtag90/Views/LoginReg/NewPassword.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Redtag90</title>
</head>
<body>
    
</body>
</html>

Redtag90/Views/LoginReg/Register.cshtml
@model User

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="~/css/register.css"/>
    <title>RedTag90</title>
</head>
<body>
    <h2 class="register_title">Create an account</h2>
    <h2 class="register_title">to start selling</h2>
    <div class="register">
        <form asp-controller="LoginReg" asp-action="Register" method="post">
            <p>First Name: </p>
            <input class="register_input" type="text" asp-for="first_name">
            <br>
            <span asp-validation-for="first_name" style="color: red;"></span>
            <br>
            <p>Last Name: </p>
            <input class="register_input" type="text" asp-for="last_name">
            <br>
            <span asp-validation-for="last_name" style="color: red;"></span>
            <br>
            <p>Email: </p>
            <input class="register_input" type="email" asp-for="email">
            <br>
            <span asp-validation-for="email" style="color: red;"></span>
            <br>
            <p>Password: </p>
            <input class="register_input" type="password" asp-for="password">
            <br>
            <span asp-validation-for="password" style="color: red;"></span>
            <br>
            <p>Confirm Password: </p>
            <input class="register_input" type="password" asp-for="confirm_password">
            <br>
            <span asp-validation-for="confirm_password" style="color: red;"></span>
            <br>
            <input type="submit" value="Register">
        </form>
        <br>
        <p>Already have an account? <a href="login">Sign-in here</a></p>
    </div>
</body>
</html>